apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service-deployment
  labels:
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: location-service:latest # We will build this image locally
          imagePullPolicy: Never # Use 'Never' for local images
          ports:
            - containerPort: 3001
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_HOST
              value: postgres-service # Kubernetes service name for PostgreSQL
            - name: DB_PORT
              value: "5432"
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  selector:
    app: location-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP